spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-candoit:3306/CANDOIT?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: candoit
  data:
    mongodb:
      uri: mongodb://candoit:candoit@mongo-candoit:27017/candoit?authSource=admin